"""Sokoban game assets, environment, and governance utilities."""

from __future__ import annotations

from .adapter import SokobanGameAdapter
from .deadlock import (
    compute_dead_squares,
    has_dead_square_deadlock,
    has_freeze_deadlock,
    is_deadlocked,
)
from .env import (
    ACTION_INDEX,
    ACTION_SPACE,
    DIRECTION_DELTAS,
    Direction,
    IllegalMoveError,
    InvalidActionError,
    InvalidLevelError,
    LevelSet,
    SokobanEnv,
    SokobanError,
    SokobanLevel,
    SokobanState,
    SokobanToolbox,
    tool_schemas,
)
from .level_loader import (
    LevelMetadata,
    LevelSetManifest,
    assert_level_governance_valid,
    count_levels_in_xsb,
    default_levels_dir,
    list_bundled_level_sets,
    load_bundled_level_set,
    load_level_by_id,
    load_level_metadata,
    load_level_set,
    parse_xsb_levels,
    validate_level_governance,
)
from .prompts import (
    DEFAULT_TEMPLATE,
    IMAGE_INSTRUCTIONS_SUFFIX,
    default_instructions,
    instructions_for_variant,
    with_image_instructions,
)
from .vision import (
    StateImage,
    render_sokoban_env_image,
    render_sokoban_image,
    render_sokoban_state_image,
)

__all__ = [
    "ACTION_INDEX",
    "ACTION_SPACE",
    "DEFAULT_TEMPLATE",
    "DIRECTION_DELTAS",
    "Direction",
    "IMAGE_INSTRUCTIONS_SUFFIX",
    "IllegalMoveError",
    "InvalidActionError",
    "InvalidLevelError",
    "LevelMetadata",
    "LevelSet",
    "LevelSetManifest",
    "SokobanEnv",
    "SokobanGameAdapter",
    "SokobanError",
    "SokobanLevel",
    "SokobanState",
    "SokobanToolbox",
    "StateImage",
    "assert_level_governance_valid",
    "compute_dead_squares",
    "count_levels_in_xsb",
    "default_levels_dir",
    "has_dead_square_deadlock",
    "has_freeze_deadlock",
    "is_deadlocked",
    "list_bundled_level_sets",
    "load_bundled_level_set",
    "load_level_by_id",
    "load_level_metadata",
    "load_level_set",
    "render_sokoban_env_image",
    "render_sokoban_image",
    "render_sokoban_state_image",
    "default_instructions",
    "instructions_for_variant",
    "parse_xsb_levels",
    "tool_schemas",
    "validate_level_governance",
    "with_image_instructions",
]
